### ISSUE TITLE
Include HTML in data.label

### ISSUE THREAD

**Issue by inovacode** [weknowinc/react-bubble-chart-d3#14]
Cool library!  I would love to use this if I can add icons inside the bubbles.  Is this possible to do in the data.label prop?

**Comment by jmsv23** [comment]
Not yet but your PR it's welcome, the only thing that you need to do it's append the svg or markup that you need on the bubble render method, hint https://github.com/weknowinc/react-bubble-chart-d3/blob/master/src/react-bubble-chart-d3.js#L193 something around this line
