### ISSUE TITLE
error NS_ERROR_FAILURE on Firefox

### ISSUE THREAD

**Issue by sonnguyent1** [weknowinc/react-bubble-chart-d3#16]
stack trace shows the error is from the code line:

> var width = self.node().getBBox().width;

**Comment by PotLid** [comment]
Just checked with latest version of package, error mentioned above is not occurring in Firefox 66.0.3 (64-bit) version. Please update your browser or re-install the package. Thanks. Please close this issue.

**Comment by enzolutions** [comment]
@sonnguyent1 could you follow the instructions, please. To see if we could close this issue.

**Comment by KenEucker** [comment]
@sonnguyent1 and @enzolutions 

I'm experiencing this issue with firefox latest and am certain that it has to do with this package.
