### ISSUE TITLE
Error on npm i @weknow/react-bubble-chart-d3

### ISSUE THREAD

**Issue by maheshk-coditas** [weknowinc/react-bubble-chart-d3#17]
Unexpected end of JSON input while parsing near '...,"d3-chord":"1","d3-c'

Error log:
22 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...,"d3-chord":"1","d3-c'
22 verbose stack     at JSON.parse (<anonymous>)
22 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
22 verbose stack     at consumeBody.call.then.buffer (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
22 verbose stack     at <anonymous>
22 verbose stack     at process._tickCallback (internal/process/next_tick.js:189:7)
23 verbose cwd C:\MaheshK\puls\web-app
24 verbose Windows_NT 10.0.10240
25 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@weknow/react-bubble-chart-d3" "--save"
26 verbose node v8.12.0
27 verbose npm  v6.4.1
28 error Unexpected end of JSON input while parsing near '...,"d3-chord":"1","d3-c'
29 verbose exit [ 1, true ]

**Comment by PotLid** [comment]
On the windows 10 / Mac OS X (Mojave), I checked there is no any other npm error is occurred. Please close this issue, thanks.
