### ISSUE TITLE
Bubbles Cut Off Regardless of Width

### ISSUE THREAD

**Issue by witang** [weknowinc/react-bubble-chart-d3#18]
Hi, I'm starting off by creating a pretty basic bubble chart with just two bubbles, each of them with some variable value. 

However, I'm finding that no matter what values I put in and that no matter how large I make the "width" prop, the bubbles are still getting cut off: 

<img width="472" alt="screen shot 2018-12-04 at 7 38 41 am" src="https://user-images.githubusercontent.com/35241613/49453503-1f7a5280-f798-11e8-9bfe-cbe22d919322.png">

Do you have any suggestions as to how to resolve this? Am I missing an additional CSS import? 

Thanks.

**Comment by jmsv23** [comment]
you can play with this values `graph= {
    zoom: 1.1,
    offsetX: -0.05,
    offsetY: -0.01,
  }` in the configuration of the graph to zoom in and zoom out the graph and the offset (x, y) that works for your particular case.

**Comment by witang** [comment]
Ah great. Thanks @jmsv23! So am I correct in assuming that the example props showing in the documentation are the "defaults"? That is, if I don't provide a graph config, it will automatically default to: 
`graph = { zoom: 1.1, offsetX: -0.05, offsetY: -0.01, }`?

**Comment by jmsv23** [comment]
Yes Thats correct

**Comment by PotLid** [comment]
#26 
Fixed issue by allowing optionally using 'overflow' style attribute for this.svg. If someone see this comments, please close the issues.
